#!/bin/bash
#SBATCH --partition=amilan # amilan (default); amem (high-mem; 96-core; <256GB)
#SBATCH --qos=normal # normal; long; mem 
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --time=1-0:00:00    
#SBATCH --job-name=cn.pr.fnd
#SBATCH --array=1-14

module purge
#module load slurm/alpine
#acompile
module load anaconda
conda activate MC0617

### Initialization
# Get Array ID
i=${SLURM_ARRAY_TASK_ID}

Rscript 3_pardep_wtr_con_11_23_non0_frstndr.R ${i}