#!/bin/bash
#SBATCH --partition=amilan # amilan (default); amem (high-mem; 96-core; <256GB)
#SBATCH --qos=normal # normal; long; mem 
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --time=0-01:00:00    
#SBATCH --job-name=pw.pr.nfnd
#SBATCH --array=1

module purge
#module load slurm/alpine
#acompile
module load anaconda
conda activate MC0617


### Initialization
# Get Array ID
i=${SLURM_ARRAY_TASK_ID}

Rscript 2_permimp_wtr_pw_11_23_hpc8_non0_nfrstndr.R ${i}