#!/bin/bash
#SBATCH --partition=amilan # amilan (default); amem (high-mem; 96-core; <256GB)
#SBATCH --qos=normal # normal; long; mem 
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --time=0-02:00:00    
#SBATCH --job-name=cn.pr.nfrdr
#SBATCH --array=1

module purge
#module load slurm/alpine
#acompile
module load anaconda
conda activate MC0617


### Initialization
# Get Array ID
i=${SLURM_ARRAY_TASK_ID}

Rscript 2_permimp_wtr_con_11_23_hpc8_non0_nfrstdr.R ${i}